sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t deltics/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true deltics/docker-react npm run test